version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-starter-frontend
    expose:
      - '3000'
    networks:
      - app-network
      - event-starter-shared

  nginx:
    image: nginx:alpine
    container_name: event-starter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
