version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: event-starter-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
